# Generated by Django 2.2.6 on 2019-10-29 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=14, verbose_name='Telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='Título')),
                ('ano_edicao', models.CharField(max_length=4, verbose_name='Ano Edição')),
                ('edicao', models.IntegerField(verbose_name='Edição')),
                ('situacao', models.BooleanField(default=False, verbose_name='Situação')),
                ('autor', models.ManyToManyField(to='cadastro.Autor')),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Editora')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtemprestimo', models.DateField(verbose_name='Data de Emprestimo')),
                ('dtdevolucao', models.DateField(verbose_name='Data de Devolução')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Livro')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Socio')),
            ],
        ),
    ]
